spring:
  application:
    name: NotificationBot
#  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: admin
#    password: password
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: true

server:
  port: 8071

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9595/eureka
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${random.uuid}
    lease-renewal-interval-in-seconds: 30