version: "3.9"

services:

  Gateway:
    container_name: Gateway
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
#    volumes:
#      - postgres:/data/postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
#    networks:
#      - postgres
