version: "3.9"

services:

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
#    volumes:
#      - postgres:/data/postgres
    restart: unless-stopped
    ports:
      - "5433:5433"
#    networks:
#      - postgres

  pgAdmin:
    container_name: pgAdmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.ru
      PGADMIN_DEFAULT_PASSWORD: password
#    volumes:
#      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"


##  networks and volumes
#  networks:
#    postgres:
#      driver: bridge

#  volumes:
#    postgres:
#    pgadmin: