spring:
  application:
    name: Inps
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: 192.168.1.220
    port: 5672
    username: guest
    password: guest

server:
  port: 808${random.int(10)}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9595/eureka
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${random.uuid}
    lease-renewal-interval-in-seconds: 30