spring:
  application:
    name: Inps
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: 192.168.1.220
    port: 5672
    username: guest
    password: guest

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9595/eureka
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${random.uuid}
    lease-renewal-interval-in-seconds: 30

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
     exposure:
       include: '*'
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      inventory:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        sliding-window-type: COUNT_BASED
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true





